name = "CoverageControllers"
uuid = "a198fc80-4b06-461c-ba50-c54cbd75a07e"
authors = ["Devansh Ramgopal Agrawal <devansh@umich.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
